### ISSUE TITLE
Android selector not available in the menu

### ISSUE THREAD

**Issue by ghatasheh** [importre/android-selector-intellij-plugin#1]
Hi, I've just installed your plugin, but I can't see Android Selector in the menu. 

Here is the error from event log
 Null child action in group New () of class class com.intellij.openapi.actionSystem.DefaultActionGroup, id=importre.intellij.android.selector.AndroidSelector

AS version is 1.4

**Comment by AKiniyalocts** [comment]
Same issue here. Grabbed the log for ya.

https://gist.github.com/AKiniyalocts/fd3d0f39cb11873edbee

**Comment by importre** [comment]
Investigating

**Comment by importre** [comment]
Fixed. I've just uploaded the plugin. :runner:
Will be updated soon!
Thank you guys for your reports.

**Comment by importre** [comment]
Please update and check it :)

**Comment by ghatasheh** [comment]
Thank you! it works fine now :+1:
